name: Build,Push to ECR and deploy to ECS

on:
  push:
    branches:
     - cicd-pipeline
env:
  ECR_REPOSITORY: 678443522600.dkr.ecr.us-west-1.amazonaws.com
  AWS_DEFAULT_REGION: us-west-1
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PORT: ${{ vars.PORT }}
  COOKIE_EXPIRE: ${{ vars.COOKIE_EXPIRE }}
  JWT_EXPIRE: ${{ vars.JWT_EXPIRE }}
  NODMAILER_EMAIL: ${{ vars.NODMAILER_EMAIL }}
  FRONTEND_URL: ${{ vars.FRONTEND_URL }}
  DB_URI: ${{ secrets.DB_URI }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  NODEMAILER_PASS: ${{ secrets.NODEMAILER_PASS }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
  MONGO_CONNECT_SECERET: ${{ secrets.MONGO_CONNECT_SECERET }}
  PLAN_PRODUCT_ID: ${{ secrets.PLAN_PRODUCT_ID }}
  Professional_monthly: ${{ secrets.Professional_monthly }}
  Professional_Yearly: ${{ secrets.Professional_Yearly }}
  Team_monthly: ${{ secrets.Team_monthly }}
  Team_Yearly: ${{ secrets.Team_Yearly }}
  MONTHLY_PROFESSIONAL_PLAN_PRICE_ID: ${{ secrets.MONTHLY_PROFESSIONAL_PLAN_PRICE_ID }}
  MONTHLY_TEAM_PLAN_PRICE_ID: ${{ secrets.MONTHLY_TEAM_PLAN_PRICE_ID }}
  Subscription_Addons: ${{ secrets.Subscription_Addons }}
  Tax_forproducts: ${{ secrets.Tax_forproducts }}
  Stripe_webhook_signing_secret: ${{ secrets.Stripe_webhook_signing_secret }}


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup ECR
      run: |
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

    - name: Build and push Docker images
      run: |    
        docker build -t ${{ env.ECR_REPOSITORY }}/onetap-backend:latest .
        docker push ${{ env.ECR_REPOSITORY }}/onetap-backend:latest
    
    - name: Display PORT value
      run: |
        echo "PORT value is $PORT"
        echo "PORT value is $NODMAILER_EMAIL"
        echo "PORT value is $DB_URI"
